name: PR:4.x

on:
    pull_request:
        branches:
            - 4.x

concurrency:
    group: OCV-PR-Linux-${{ github.ref }}
    cancel-in-progress: true

jobs:
    Ubuntu:
        runs-on: incredibuild-runner
        permissions:
            contents: read

        defaults:
            run:
                shell: bash
        container:
            image: "quay.io/opencv-ci/opencv-ubuntu-24.04:20251127"

        env:
            CCACHE_MAXSIZE: "8G"
            CMAKE_OPT: >-
                -DBUILD_DOCS=ON
                -DBUILD_EXAMPLES=ON
                -DOPENCV_ENABLE_NONFREE=ON
                -DWITH_IMGCODEC_GIF=ON
            MAIN_BUILD_DIR: "${{ (github.event.repository.name != 'opencv_contrib') && 'build' || 'build-contrib' }}"
            OPENCV_FOR_THREADS_NUM: 4
            CMAKE_BUILD_PARALLEL_LEVEL: 4
            IB_ACCEL_DEBUG: 1

        steps:
            - name: Checkout workflow repository
              uses: actions/checkout@v4
              with:
                  repository: opencv/ci-gha-workflow
                  ref: main

            - name: Checkout and merge OpenCV
              uses: ./checkout-and-merge
              with:
                  target_branch: "4.x"
                  author: "${{ github.event.pull_request.user.login }}"
                  source_branch: "${{ github.head_ref }}"
                  home: "${{ github.workspace }}"
                  workdir: "${{ github.workspace }}"

            - name: Create cache directories
              run: |
                  mkdir -p "$GITHUB_WORKSPACE/.ccache"
                  mkdir -p "$GITHUB_WORKSPACE/binaries_cache"

            - if: ${{ github.event.repository.name != 'opencv_contrib' }}
              name: Configure OpenCV
              run: |
                  echo "::group::Configure"
                  cd "$GITHUB_WORKSPACE"
                  rm -rf build
                  mkdir -p build
                  cmake \
                    -S opencv \
                    -B build \
                    -G Ninja \
                    ${{ env.CMAKE_OPT }}
                  echo "::endgroup::"

            - if: ${{ github.event.repository.name != 'opencv_contrib' }}
              name: Build OpenCV
              run: |
                  set -x
                  echo "::group::Build"
                  cd "$GITHUB_WORKSPACE"
                  cmake --build build 2>&1 | tee build/log.txt
                  echo "::endgroup::"

            - if: ${{ github.event.repository.name != 'opencv_contrib' }}
              name: Check build warnings
              run: |
                  set +e
                  python3 ./scripts/warnings-handling.py \
                    "$GITHUB_WORKSPACE/build/log.txt"
                  if [ $? -ne 0 ]; then
                    echo "WARNINGS=1" >> $GITHUB_ENV
                  fi

            - name: Configure OpenCV with contrib
              run: |
                  echo "::group::Configure"
                  cd "$GITHUB_WORKSPACE"
                  rm -rf build-contrib
                  mkdir -p build-contrib
                  cmake \
                    -S opencv \
                    -B build-contrib \
                    -G Ninja \
                    -DOPENCV_EXTRA_MODULES_PATH=opencv_contrib/modules \
                    ${{ env.CMAKE_OPT }}
                  echo "::endgroup::"

            - name: Build OpenCV with contrib
              run: |
                  set -x
                  echo "::group::Build"
                  cd "$GITHUB_WORKSPACE"
                  cmake --build build-contrib 2>&1 | tee build-contrib/log.txt
                  echo "::endgroup::"

            - name: Check build-contrib warnings
              run: |
                  set +e
                  python3 ./scripts/warnings-handling.py \
                    "$GITHUB_WORKSPACE/build-contrib/log.txt"
                  if [ $? -ne 0 ]; then
                    echo "WARNINGS=1" >> $GITHUB_ENV
                  fi

            - if: ${{ always() && env.WARNINGS == '1' }}
              name: Warnings check
              run: |
                  echo "::error Warnings have been found!"
                  exit 1
